config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  get 'books/:id' => 'books#show', as: 'book'



  resources :books, only: [:create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:index, :show, :edit, :update]



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user, optional: true

    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  attachment :profile_image
  attachment :user

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?



  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :baria_user, only: [:edit, :update, :destroy]

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all

  end

  def show
    @book = Book.find(params[:id])
    @books = Book.all
    @user = @book.user
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path, notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def baria_user
    unless Book.find(params[:id]).user.id.to_i == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_current_user, {only: [:edit, :update]}
  def ensure_current_user
    if current_user.id != params[:id].to_i
      redirect_to user_path(@current_user.id)
    end
  end



  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = Book.new

  end

  def index
    @user = current_user
    @books = Book.all
    @users = User.all
    @book = Book.new

  end

  def edit
    @user = User.find(params[:id])
    @book = Book.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def users
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_info.html.erb
<h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    <table class="table">
      <tbody>
        <tr></tr>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th>
            <%= user.introduction %>
          </th>
        </tr>
      </tbody>
    </table>

app/views/books/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-o mx-auto">
  <h1>Editing Book</h1>
  <div id="error_explanation">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>
  </div>
  
  <%= form_with model:@book, local:true do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title, autofocus: true, id:"booktitle",  :class => 'form-control' %>
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, autofocus: true, id:"bookopinion",  :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit "Update Book", :class => 'btn btn-success'  %>  
    </div>
  <% end %>
  <%= link_to @book do %>
    Show
  <% end %>
  |
  <%= link_to "/books" do %>
    Back
  <% end %>
</div>

app/views/books/index.html.erb
<div id="error_explanation">
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
</div>

<div class="row">
  <div class="col-md-3">
    <%= render 'books/info', user: current_user %>


    <%= link_to edit_user_path(current_user), class: 'btn btn-outline-secondary btn-block' do %>
    <i class="fas fa-user-cog"></i>
    <% end %>


    <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <label>Title</label>
    　     <%= f.text_field :title, :class => 'form-control'%>
        </div>
        <div class="form-group">
          <label>Opinion</label>
    　     <%= f.text_area :body, :class => 'form-control'%>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', :class => 'btn btn-success' %>
        </div>
      <% end %>
  </div>

  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </thead>
      <% @books.each do |book| %>
      <tbody>
        <tr>
          <td>
            <%= link_to user_path(book.user_id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'64x64'  %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td><%= book.body %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'books/info', user: @user %>


    <%= link_to edit_user_path(@user), class: 'btn btn-outline-secondary btn-block' do %>
    <i class="fas fa-user-cog"></i>
    <% end %>


    <h2 class="mt-3">New book</h2>
      <%= form_with model: Book.new, local:true do |f| %>
        <div class="form-group">
          <label>Title</label>
    　     <%= f.text_field :title, :class => 'form-control'%>
        </div>
        <div class="form-group">
          <label>Opinion</label>
    　     <%= f.text_area :body, :class => 'form-control'%>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', :class => 'btn btn-success' %>
        </div>
      <% end %>
  </div>

  <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table table-hover table-inverse">
      <tbody>
        <tr>
          <td>
            <%= link_to user_path(@user) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 40, 56, format: 'jpeg', fallback: "no_image.jpg", size: '40x40'  %>
              <br><%= @user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@book) do %>
              <%= @book.title %>
            <% end %>
          </td>
          <td><%= @book.body %></td>
          
          <% if @user.id == current_user.id %>
            <td>
              <%= link_to edit_book_path(@book), class: 'btn btn-sm btn-success' do %>
                Edit
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book), method: :delete, class: 'btn btn-sm btn-danger' do %>
                Destroy
              <% end %>
            </td>
          <% end %>
          <td>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
        welcome to 
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
         !
      </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
  <h1>
    welcome to
    <i class="fas fa-book"></i>
    <strong>Bookers</strong>
    !!
  </h1>
  <p>
    In
    <i class="fas fa-book"></i>
    <storong>Bookers</storong>
     ,
  </P>
  <p>you can share and exchange your opinions, inporessions , and emotions</p>
  <p>about various books!</p>
  <div class="btn-wrapper col-10 mx-auto">
    <div clas="row">
      <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
    </div>
    <div clas="row">
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
     </div>
  </div>
</div>

app/views/layouts/_noticifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: #{key) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/53794c647f.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler text-muted" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to ' Home', user_path(current_user.id), class: 'fas fa-home nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to ' Users', href="/users", class: 'fas fa-users nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to ' Books', href="/books", class: 'fas fa-book-open nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to " logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-white' %>
            </li>
            <% else %>
            <li>
              <%= link_to ' Home', href="/", class: 'fas fa-home nav-link text-white' %>
            </li>
            <li>
              <%= link_to " About", href="/home/about", class: 'fas fa-link nav-link text-white' %>
            </li>
            <li>
              <%= link_to " Sign up", new_user_registration_path, class: 'fas fa fa-user-plus nav-link text-white' %>
            </li>
            <li>
              <%= link_to " Login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-white' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>

      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <div class="container px-5 px-sm-0">
        <%= yield %>
      </div>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-o mx-auto">
  <h2>User info</h2>
  
  <div id="error_explanation">
    <% if @user.errors.any? %>
      <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>
  </div>
  
  <%= form_with model:@user, local:true do |f| %>
    <div class="form-group">
      <label for="user_name">Name</label>
      <%= f.text_field :name, autofocus: true, id:"username", :class => 'form-control' %>
    </div>
    <div class="form-group">
      <label for="user_Image">Image</label>
      <%= f.attachment_field :profile_image, id:"profile_image", placeholder: "プロフィール画像", :class => 'form-control-file' %>
    </div>
    <div class="form-group">
      <label for="user_introduction">Introduction</label>
      <%= f.text_area :introduction, autofocus: true, id:"user_introduction", :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit "Update User", :class => 'btn btn-secondary'  %>  
    </div>

  <% end %>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'books/info', user: @user %>


    <%= link_to edit_user_path(current_user), class: 'btn btn-outline-secondary btn-block' do %>
    <i class="fas fa-user-cog"></i>
    <% end %>


    <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <label>Title</label>
    　     <%= f.text_field :title, :class => 'form-control'%>
        </div>
        <div class="form-group">
          <label>Opinion</label>
    　     <%= f.text_area :body, :class => 'form-control'%>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', :class => 'btn btn-success' %>
        </div>
      <% end %>
  </div>

  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
          </td>
          <td>
            <%= user.name %>
          </td>
          <td>
            <%= link_to user_path(user.id) do %>
               Show
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'books/info', user: @user %>


    <%= link_to edit_user_path(@user), class: 'btn btn-outline-secondary btn-block' do %>
    <i class="fas fa-user-cog"></i>
    <% end %>


    <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <label>Title</label>
    　     <%= f.text_field :title, :class => 'form-control'%>
        </div>
        <div class="form-group">
          <label>Opinion</label>
    　     <%= f.text_area :body, :class => 'form-control'%>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', :class => 'btn btn-success' %>
        </div>
      <% end %>
  </div>

  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </thead>
      <% @books.each do |book| %>
      <tbody>
        <tr>
          <td>
            <%= link_to user_path(book.user_id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td><%= book.body %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>